import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../common/prisma.service';
import { ForecastService } from '../forecast/forecast.service';
import { CurrentUserData } from '../common/decorators/current-user.decorator';

@Injectable()
export class ReplenishmentService {
  private readonly logger = new Logger(ReplenishmentService.name);

  constructor(
    private prisma: PrismaService,
    private forecastService: ForecastService,
  ) {}

  /**
   * Scans all products, checks their forecast against current stock,
   * and generates DRAFT Purchase Orders if stock is predicted to go below zero.
   */
  async runAutoReplenishment(currentUser: CurrentUserData) {
    this.logger.log('Starting auto-replenishment process...');
    
    // 1. Get all active products with their current inventory and assigned vendor
    const products = await this.prisma.product.findMany({
      where: { isActive: true },
      include: { 
        inventory: true,
        vendor: true 
      }
    });

    const draftPOs: any[] = [];

    for (const product of products) {
      const currentStock = product.inventory.reduce((sum, i) => sum + i.quantity, 0);
      
      try {
        let needsReplenishment = false;
        let replenishmentQty = 0;

        try {
          // 2. Get forecast for the next 6 months to be proactive
          const forecastResult = await this.forecastService.forecast(product.sku, 6, currentUser);
          
          // 3. Check if predicted stock goes below zero
          let projectedStock = currentStock;

          for (const f of forecastResult.forecasts) {
            projectedStock -= f.predicted;
            if (projectedStock < 0) {
              needsReplenishment = true;
              replenishmentQty = Math.abs(projectedStock) + (product.reorderThreshold || 10);
              break;
            }
          }
        } catch (mlError) {
           this.logger.warn(`Forecast unavailable for ${product.sku}, using standard reorder points. (${mlError.message})`);
           if (currentStock < (product.reorderThreshold || 10)) {
               needsReplenishment = true;
               replenishmentQty = (product.reorderThreshold || 10) * 2 - currentStock;
           }
        }

        if (needsReplenishment && product.vendorId) {
          // Check if there is already a DRAFT or PENDING PO for this product to avoid duplicates
          const existingPO = await this.prisma.purchaseOrder.findFirst({
            where: {
              vendorId: product.vendorId,
              status: { in: ['DRAFT', 'PENDING'] },
              lines: {
                some: { productId: product.id }
              }
            }
          });

          if (!existingPO) {
            // 4. Generate DRAFT PO
            const po = await this.createDraftPO(product, replenishmentQty, currentUser);
            draftPOs.push(po);
            this.logger.log(`Created DRAFT PO ${po.orderNumber} for product ${product.sku}. Replenishment Qty: ${replenishmentQty}`);
          } else {
            this.logger.debug(`Skipping auto-PO for ${product.sku}: Active PO ${existingPO.orderNumber} already exists.`);
          }
        }
      } catch (error) {
        this.logger.error(`Failed to process replenishment for ${product.sku}: ${error.message}`);
      }
    }

    return {
      success: true,
      message: `Auto-replenishment completed. Created ${draftPOs.length} draft purchase orders.`,
      count: draftPOs.length
    };
  }

  private async createDraftPO(product: any, quantity: number, currentUser: CurrentUserData) {
    const tenantId = product.tenantId;
    
    // Generate a unique order number
    const count = await this.prisma.purchaseOrder.count({ where: { tenantId } });
    const orderNumber = `AUTO-PO-${Date.now()}-${count + 1}`;

    const unitPrice = Number(product.unitPrice);
    const uomFactor = Number(product.purchaseFactor || 1.0);
    const orderQty = Math.ceil(quantity / uomFactor);

    return this.prisma.purchaseOrder.create({
      data: {
        orderNumber,
        status: 'DRAFT',
        vendor: { connect: { id: product.vendorId } },
        tenant: { connect: { id: tenantId } },
        createdBy: { connect: { id: currentUser.id } },
        notes: 'Automatically generated by ReplenishmentService based on AI demand forecast.',
        totalAmount: orderQty * unitPrice,
        lines: {
          create: [{
            product: { connect: { id: product.id } },
            quantity: orderQty,
            unitPrice: unitPrice,
            totalPrice: orderQty * unitPrice,
            uom: product.purchaseUnit || 'ea',
            uomFactor: uomFactor,
            tenant: { connect: { id: tenantId } },
          }]
        }
      }
    });
  }
}
